/**
 * Property-Based Test: Collection endpoints return an empty success envelope
 * when nothing matches.
 *
 * Feature: communication-feedback-and-admin-apis, Property 25: Collection endpoints return an empty success envelope when nothing matches
 *
 * Property 25: For any collection-returning new endpoint whose in-scope record
 * set is empty, the response is HTTP 200 with a success envelope whose `data`
 * is an empty collection.
 *
 * Strategy: this property is exercised at the service level (the layer that the
 * controllers wrap verbatim in `success()`). For arbitrary authenticated user
 * identifiers and arbitrary pagination, with no matching records in the
 * database, each collection-returning service must return an empty `data`
 * collection and a `total` of zero. `feedbackService.listReceived`
 * additionally exposes aggregate statistics, which must be fully zeroed when
 * the in-scope set is empty (Requirement 7.5 / 8.5 zeroed stats). Because the
 * services always resolve (never throw) for an empty in-scope set, the wrapping
 * controllers produce HTTP 200 success envelopes — the observable behavior the
 * property asserts.
 *
 * The in-scope set is forced empty by clearing all four backing collections per
 * run and querying with random, freshly generated identifiers that match no
 * seeded document, so the result is independent of any prior corpus.
 *
 * **Validates: Requirements 1.7, 7.5, 12.6**
 */

import { describe, it, expect, beforeAll, afterAll, beforeEach } from '@jest/globals';
import * as fc from 'fast-check';
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';

import { messageService } from './messageService.js';
import { feedbackService } from './feedbackService.js';
import { parentService } from './parentService.js';
import Message from '../models/Message.js';
import Feedback from '../models/Feedback.js';
import Parent from '../models/Parent.js';

// ---------------------------------------------------------------------------
// MongoDB memory server setup
// ---------------------------------------------------------------------------

let mongoServer: MongoMemoryServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  await mongoose.connect(mongoServer.getUri());
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongoServer.stop();
});

beforeEach(async () => {
  await Promise.all([
    Message.deleteMany({}),
    Feedback.deleteMany({}),
    Parent.deleteMany({}),
  ]);
});

// ---------------------------------------------------------------------------
// Arbitraries
// ---------------------------------------------------------------------------

// A valid 24-hex-character ObjectId string. Generated by fast-check so the
// caller identity is genuinely arbitrary while remaining a castable ObjectId.
const HEX_DIGITS = '0123456789abcdef';
const objectIdHexArb = fc
  .array(fc.constantFrom(...HEX_DIGITS.split('')), {
    minLength: 24,
    maxLength: 24,
  })
  .map((chars) => new mongoose.Types.ObjectId(chars.join('')).toString());

// Arbitrary 1-based pagination. Values intentionally span beyond the first
// page and beyond the 100-row cap to confirm emptiness holds for any page.
const pageArb = fc.integer({ min: 1, max: 50 });
const limitArb = fc.integer({ min: 1, max: 200 });

// ---------------------------------------------------------------------------
// Property 25
// ---------------------------------------------------------------------------
// Feature: communication-feedback-and-admin-apis, Property 25: Collection endpoints return an empty success envelope when nothing matches
describe('Property 25: Collection endpoints return an empty success envelope when nothing matches', () => {
  it('every collection service returns an empty data collection (total 0; listReceived zeroed stats) when nothing matches', async () => {
    await fc.assert(
      fc.asyncProperty(
        objectIdHexArb,
        fc.constantFrom('teacher' as const, 'parent' as const),
        fc.constantFrom('student' as const, 'parent' as const),
        pageArb,
        limitArb,
        async (userId, conversationRole, authorRole, page, limit) => {
          // Force the in-scope set empty for every backing collection so the
          // result depends only on the absence of matching records.
          await Promise.all([
            Message.deleteMany({}),
            Feedback.deleteMany({}),
            Parent.deleteMany({}),
          ]);

          // --- Messaging: list conversations (Requirement 1.7) -------------
          const conversations = await messageService.listConversations(
            userId,
            conversationRole,
            page,
            limit,
          );
          expect(Array.isArray(conversations.data)).toBe(true);
          expect(conversations.data).toEqual([]);
          expect(conversations.total).toBe(0);

          // --- Feedback: own-feedback listing (Requirement 7.5) ------------
          const own = await feedbackService.listOwn(
            userId,
            authorRole,
            page,
            limit,
          );
          expect(Array.isArray(own.data)).toBe(true);
          expect(own.data).toEqual([]);
          expect(own.total).toBe(0);

          // --- Feedback: received-feedback listing with zeroed stats -------
          // (Requirement 8.5: empty collection + zeroed Feedback_Stats.)
          const received = await feedbackService.listReceived(
            userId,
            page,
            limit,
          );
          expect(Array.isArray(received.data)).toBe(true);
          expect(received.data).toEqual([]);
          expect(received.total).toBe(0);
          expect(received.stats).toEqual({
            total: 0,
            positive: 0,
            needsAttention: 0,
            averageRating: 0,
          });

          // --- Admin parents list (Requirement 10.5 / 12.6) ---------------
          const parents = await parentService.list(
            {},
            { page, limit },
          );
          expect(Array.isArray(parents.data)).toBe(true);
          expect(parents.data).toEqual([]);
          expect(parents.meta.total).toBe(0);
        },
      ),
      { numRuns: 100 },
    );
  });
});
